### ISSUE TITLE
Add a function to delete players from the scoreboard.

### ISSUE THREAD

**Issue by ynohtna92** [Infekma/D2ScoreBoard#1]
Right now as a workaround I am deleting the whole scoreboard and rebuilding it every time a player changes. Not ideal and looks hacky in-game since the whole scoreboard flashes.

Or at least allow a way to soft replace the scoreboard so the table can rebuild without deleting with Async.

**Comment by Infekma** [comment]
ScoreBoard:DeletePlayer(playerid)
