### ISSUE TITLE
Allow editing of team headers using alias name

### ISSUE THREAD

**Issue by ynohtna92** [Infekma/D2ScoreBoard#2]
For example if I wanted to change the header so it matches 'Sheep: 1' I would have to create it as such. 

![wc3_st_lb2](https://cloud.githubusercontent.com/assets/2245318/9537658/61076822-4d7e-11e5-8b4c-41739cafa6e5.PNG)

**Comment by Infekma** [comment]
Hey, I've added the functionaity to support this, if you update your scoreboard.lua and scoreboard.js you should be able to use this to change the name of the header:

      ScoreBoard:Edit({key="SECTION_HEADER", header="The Mighties", text="Sheep: 2"})

-- Infekma
